#!/bin/bash

set -e

DENO_VERSION='v1.13.1'
export PATH=/vercel/.deno/bin:$PATH

curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
deno run -A https://deno.land/x/aleph/install.ts
aleph build
